version: '3.9'

services:

  mysql-mycrud:
    # Defino a imagem e a versão
    image: mysql:5.7
    
    #Defino o local da persistência dos dados e usados pelo contêiner
    container_name: mysql-mycrud

    #Defino o local da persistência dos dados e usados pelo container do docker.(depende da estrutura do diretório)
    volumes:
      - ./db:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./docker-config/mysql/init.sql:/etc/script-db-mycrud/init.sql
    command: --init-file /etc/script-db-mycrud/init.sql

    #Define a porta que o mysql está rodando dentro do container
    ports: 
      - '3306:3306'

    #Abre a porta 3306 no container
    #expose:
    #  - '3306'

    # Variáveis de ambiente
    environment:
      #Nome de identificação do database
      MYSQL_DATABASE: 'my_crud'
      #Senha para o acesso root
      MYSQL_ROOT_PASSWORD: 'mypass'

  nginx-mycrud:
    #Define imagem e nome do container
    image: nginx
    container_name: nginx
    #Define a porta padrão 
    ports:
      - '80:80'
    #Define o diretório das configurações do server nginx:define o diretório(container) onde a conf do nginx se estabelecerá.

    #Defino o diretório do conteúdo frontend que irá para o container:defino o diretório onde o conteúdo frontend estará estabelecido no container.(por padrão, é a var/www/html) 
    volumes:
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html

  node:
    image: node
    container_name: node
    ports:
      - '9001:9001'
    volumes:
      #Bind Volume
      - ./backend:/application
      - ./docker-config/node/start_application.sh:/node/start_application.sh
    depends_on:
      - mysql-mycrud
    entrypoint: /node/start_application.sh
